<<<<<<< HEAD
import Head from 'next/head';
import styles from '../styles/Home.module.css';
=======
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../pages/Header/Header";
import Footer from "../pages/Footer/Footer";
>>>>>>> 1c8c9e5386ffe8b6f811be7c886f2ee733183129

import HomePage from './Home/HomePage';

export default function Index() {
  return (
    <div className={styles.container}>
      <Head>
        <title>PortraitScopie - Myrhmica</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
<<<<<<< HEAD
        <HomePage />
=======
        <Header />
        <Footer />
>>>>>>> 1c8c9e5386ffe8b6f811be7c886f2ee733183129
      </main>
    </div>
  );
}
